name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        laravel: [10.0]
    name: P${{ matrix.php }} - L${{ matrix.laravel }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite
        coverage: none
    - name: Create Laravel app
      run: composer create-project laravel/laravel=${{ matrix.laravel }} ../app --prefer-dist
    - name: Change stability to dev
      run: |
        cd ../app
        sed -i 's/"minimum-stability": "stable"/"minimum-stability": "dev"/' composer.json
    - name: Install dependencies
      run: |
        cd ../app
        composer require devdojo/genesis dev-main
    - name: Install all dependencies
      run: |
        composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Install preset
      run: |
        cd ../app
        php artisan ui genesis

    - name: List contents
      run: |
        cd ../app/vendor/bin
        ls -la

    - name: Execute tests
      run: |
        cd ../app
        vendor/bin/pest
